.\" Copyright (C) 2017 Kevin Boone 
.\" Permission is granted to any individual or institution to use, copy, or
.\" redistribute this software so long as all of the original files are
.\" included, that it is not sold for profit, and that this copyright notice
.\" is retained.
.\"
.TH dbcmd-usage 1 "May 2017"
.SH NAME
Show quota and usage on the dropbox server

.SH SYNOPSIS
.B dbcmd 
usage
.PP

.SH DESCRIPTION

This command reports the space allocated on the Dropbox server, and
the amounts that are used and available.

.SH "OPTIONS"

See main manual page.


.SH SEE ALSO 

.SS \fIdbcmd(1)\fR 


.\" end of file
